<form action="article.php" method="post">
	<h2>{$action_label} un article</h2>
	<div class="clearfix">
		{if isset($erreur)}
			<div class='alert alert-error'>
			Veuillez saisir tous les champs.
			</div>	
		{/if}

	<label for="titre">Titre</label>
		<div class="input">
			<input type="text" name="titre" id="titre" value="{if isset($rep['titre'])} {$rep['titre']}{/if}">
		</div> 
	</div>
	<div class="clearfix">
		<label for="texte">Texte</label>
		<div class="input">
			<textarea name="texte" id="texte">{if isset($rep['texte'])} {$rep['texte']}{/if}</textarea>
		</div> 
	</div>
	<div class="clearfix">
		<div class="input">
			<input type="checkbox" name="publie" id="publie" value="1"><label for="publie">Publier</label>
		</div> 
	</div>
	
	<div class="clearfix">
		<label for="tag">Tag</label>
		<div class="input">
			<input type="text" name="tag" id="tag" value="{if isset($rep['tag'])} {$rep['tag']}{/if}">
		</div> 
	</div>
		<!-- test -->
	<form action="article.phtml" method="post" enctype="multipart/form-data" name="upload">
		<div class="input"><input type='hidden' name='upload' value='1'></div>
		<div class="clearfix">
			<input type="file" name="image" id="image">
		</div>
		
	<div class="form-actions">
		<input type="submit" value="{$action_label}" class="btn btn-large btn-primary"> 
		<input type="hidden" name='post' value=""> <!-- Permet de savoir si on se trouve en traitement -->
		<input type="hidden" name='id' value="{$id}"> <!-- Permet de savoir si on se trouve en modification -->
	</div>
	
	
</form>

